"""Add TagIcon To tags and SocialLinks to User model

Revision ID: 19cc5de37ca5
Revises: 60e5a0e7e0b3
Create Date: 2025-07-21 22:13:18.330360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cc5de37ca5'
down_revision = '60e5a0e7e0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('website_url')
        batch_op.drop_column('github_url')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
