"""Bio field Added to User Table

Revision ID: 627490131cea
Revises: 19cc5de37ca5
Create Date: 2025-07-22 01:31:41.548063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627490131cea'
down_revision = '19cc5de37ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
