"""Add Hackathon Judges Table

Revision ID: c42b818d19b5
Revises: 627490131cea
Create Date: 2025-07-22 12:52:39.281909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42b818d19b5'
down_revision = '627490131cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hackathon_judges')
    # ### end Alembic commands ###
